export const commons = {
  stacks: [
    { skill: 'html', proficiency: 70 },
    { skill: 'css', proficiency: 85 },
    { skill: 'javascript', proficiency: 90 },
    { skill: 'typescript', proficiency: 70 },
    { skill: 'react', proficiency: 85 },
    { skill: 'redux', proficiency: 70 },
    { skill: 'jest', proficiency: 75 },
    { skill: 'React Testing Library', proficiency: 75 },
    { skill: 'Styled Components', proficiency: 80 },
    { skill: 'sass', proficiency: 35 },
    { skill: 'eslint', proficiency: 65 },
    { skill: 'miragejs', proficiency: 70 },
    { skill: 'msw', proficiency: 70 },
    { skill: 'prettier', proficiency: 65 },
    { skill: 'stylelint', proficiency: 65 },
    { skill: 'tailwind', proficiency: 45 },
    { skill: 'axios', proficiency: 70 },
    { skill: 'webpack', proficiency: 70 },
    { skill: 'zustand', proficiency: 75 },
  ],
};
